[plugin]
repository = "https://github.com/itsbexy/gaugeomatic.git"
commit = "50b5b21591705fb9b53bb80df240ccf4afacff5e"
owners = [
    "ItsBexy",
]
changelog = """
Restored the functionality of VPR gauge data and the *Color-Code Vipersight* tweak
"""
