[plugin]
repository = "https://github.com/itsbexy/gaugeomatic.git"
commit = "abf0840d561c96847e473b0ffd9f8eebe9bd97f5"
owners = [
    "ItsBexy",
]
changelog = """
Fixed an issue where widgets pinned to certain gauges would not load when switching jobs.
"""
