[plugin]
repository = "https://github.com/itsbexy/gaugeomatic.git"
commit = "c59ef436ff080ec3a6641c6683ef2fc575b328cb"
owners = [
    "ItsBexy",
]
changelog = """
## TWEAKS
- **New Tweak for BLM:** *Color MP Bar By Element*

## MISC FIXES
- Fixed (?) an issue preventing Level Range rules from loading or editing correctly
"""
