[plugin]
repository = "https://github.com/itsbexy/gaugeomatic.git"
commit = "1b9115f7d81a7942c4036745ad3ae7c2789430b1"
owners = [
    "ItsBexy",
]
changelog = """
Gauge-O-Matic allows you to customize your job gauges with additional counters, bars, and indicators in a variety of styles. Each widget design has unique options to control its style and behaviour, and the plugin allows for importing/exporting/sharing collections of widgets as presets.
"""
