[plugin]
repository = "https://github.com/itsbexy/gaugeomatic.git"
commit = "2b4d5e59db555db80c9b3c93e463eed34a379efa"
owners = [
    "ItsBexy",
]
changelog = """
Gauge-O-Matic allows you to customize your job gauges with additional counters, bars, and indicators in a variety of styles. Each widget design has unique options to control its style and behaviour, and the plugin allows for importing/exporting/sharing collections of widgets as presets.
"""
